# Generated by Django 2.0.2 on 2018-04-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date_time', models.DateTimeField(verbose_name='Record received')),
                ('raw_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_change_date_time', models.DateTimeField(verbose_name='Status changed')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
