# Generated by Django 2.0.2 on 2018-04-25 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 23, 0, 560294)),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 23, 0, 559823)),
        ),
    ]
