# Generated by Django 2.0.2 on 2018-04-25 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcp', '0002_auto_20180425_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='alarm',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 28, 41, 915406)),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 28, 41, 914904)),
        ),
    ]
