# Generated by Django 2.0.2 on 2018-04-25 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcp', '0003_auto_20180425_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='location',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 29, 26, 470115)),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 29, 26, 469612)),
        ),
    ]
