# Generated by Django 2.0.2 on 2018-04-25 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcp', '0004_auto_20180425_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 43, 12, 14027)),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 43, 12, 13560)),
        ),
    ]
