# Generated by Django 2.0.2 on 2018-04-28 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcp', '0005_auto_20180425_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 12, 0, 42, 324300)),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 12, 0, 42, 323298)),
        ),
    ]
